import BodySegments from './components/BodySegments/BodySegments'
import SectionHeadline from './components/SectionHeadline/SectionHeadline'

export BodySegments from './components/BodySegments'
import { Segment } from './components/BodySegments'
export const BodySegment = Segment
export CallToActionSection from './components/CallToActionSection'
export Footer from './components/Footer'
export FreeTrial from './components/FreeTrial'
export Hero from './components/Hero'
export ListItem from './components/ListItem'
export MediaContent from './components/MediaContent'
export Navigation from './components/Navigation'
export Quote from './components/Quote'
export SectionHeadline from './components/SectionHeadline'
export SocialButton from './components/SocialButton'
export SocialProof from './components/SocialProof'
